version: "3.9"

services:
  nextjs:
    build: .
    container_name: nextjs-app
    ports:
      - "9998:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    restart: unless-stopped
